<?php

/**
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL).
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   	Payment Gateway
 * @package    	MercadoPago
 * @author      André Fuhrman (andrefuhrman@gmail.com)
 * @copyright  	Copyright (c) MercadoPago [http://www.mercadopago.com]
 * @license    	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>

<fieldset class="form-list">
    <?php  $_code=$this->getMethodCode(); ?>
    <?php $_country = $this->getMethodCountry(); ?>

<ul id="payment_form_<?php  echo $_code ?>" >
        <li>
        <?php if($this->getMethod()->getConfigData('acc_origin') == 'MLB'): ?>    
           <img src="<?php echo $this->getSkinUrl('images/mercadopago/mercadopagobr.jpg'); ?>" alt="MercadoPago" title="MercadoPago" />
        <?php else: ?>   
            <img src="<?php echo $this->getSkinUrl('images/mercadopago/mercadopagoar.jpg'); ?>" alt="MercadoPago" title="MercadoPago" />
        <?php endif; ?> 
        </li>
</ul>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>




